import type {Metadata} from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {Outfit} from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ['latin'],
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true"
        className={`antialiased ${outfit.className} `}
      >
        <>
          <Navbar />
          {children}
        </>
      </body>
    </html>
  );
}
